name: Deploy to Azure Static WebApp

on:
  push:
    branches:
      - master

jobs:
  Create_Infrastructure:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: "Replace secret token in Setup.sh"
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: "__token__"
          replace: ${{ secrets.PAT }}$

      - name: "Make Setup.sh an executable"
        run: chmod 754 azure-resources/setup.sh

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET }}

      - name: "Run Setup.sh"
        run: ./azure-resources/setup.sh
